# Generated by Django 3.1.1 on 2020-09-17 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estore', '0004_auto_20200918_0207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
